name: Label Proposals

on:
  issues:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add label to new CFP issues
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = context.payload.issue.title;
            const issueNumber = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            console.log(`Issue title: ${issueTitle}`);

            // Add the label if the issue title contains 'Talk Title'
            if (issueTitle.includes('Talk Title')) {
              console.log('Adding label...');
              await github.issues.addLabels({
                owner: owner,
                repo: repo,
                issue_number: issueNumber,
                labels: ['proposal-submitted']
              });
            } else {
              console.log('No label added.');
            }
